Show ideas
MiBBy-4/ideas_api_frontend pull request #2
Opened 2022-02-02 13:31 UTC by MiBBy-4

2022-02-03 06:16 UTC, AndreyAnischik requested changes

2022-02-03 06:16 UTC, AndreyAnischik commented on src/Idea/IdeaForm.jsx
> +class IdeaForm extends Component {
use functional components and hooks

2022-02-03 06:16 UTC, AndreyAnischik commented on src/Idea/IdeaList.jsx
> +class IdeaList extends Component {
functional component

2022-02-04 07:09 UTC, AndreyAnischik requested changes

2022-02-04 07:09 UTC, AndreyAnischik commented on src/Idea/IdeaForm.jsx
> +    setName(event.target.value);
make object destructuring (https://dmitripavlutin.com/javascript-object-destructuring/) before setting the values and move it to a separate var

2022-02-04 07:09 UTC, AndreyAnischik commented on src/Idea/IdeaForm.jsx
> +    setName(event.target.value);
won't it set same values for all the fields?

2022-02-04 07:09 UTC, AndreyAnischik commented on src/Idea/IdeaForm.jsx
> +    await fetch(apiURL, {
make single entry for all endpoints (move fetch functionality to a separate file and use it from other components too

2022-02-04 07:09 UTC, AndreyAnischik commented on src/Idea/IdeaList.jsx
> +      .then((responseItems) => {
move it a separate file (the same file as for POST requests)

2022-02-04 07:09 UTC, AndreyAnischik commented on src/Idea/IdeaList.jsx
> +const apiURL = 'http://localhost:3000/api/v1/ideas';
move BASE_URL to an .env file

2022-02-04 07:09 UTC, AndreyAnischik commented on src/Idea/IdeaList.jsx
> +      <IdeaForm apiURL={apiURL} updateIdeaList={updateIdeaList} />
you don't need to pass apiUrl when it will be in a constant and a separate file

2022-02-04 10:06 UTC, MiBBy-4 commented on src/Idea/IdeaForm.jsx
> +    setName(event.target.value);
Yeap, I think it. I did it only for test, I will change it.

2022-02-07 07:23 UTC, AndreyAnischik commented on src/Idea/IdeaFetch.jsx
> +  console.log('Inside postFetchResponse');
remove log please

2022-02-07 07:25 UTC, AndreyAnischik requested changes

2022-02-07 07:25 UTC, AndreyAnischik commented on src/Idea/IdeaForm.jsx
> +    setName(event);
you need to set value here

2022-02-07 07:25 UTC, AndreyAnischik commented on src/Idea/IdeaForm.jsx
> +    console.log('Inside formSubmit');
remove log

2022-02-07 07:25 UTC, AndreyAnischik commented on src/Idea/IdeaForm.jsx
> +  const [apiURL, setApiURL] = useState(process.env.REACT_APP_API_URL);
do you use this var?

2022-02-07 10:10 UTC, MiBBy-4 commented on src/Idea/IdeaForm.jsx
> +  const [apiURL, setApiURL] = useState(process.env.REACT_APP_API_URL);
No, sorry. I always forget about this

2022-02-07 15:30 UTC, AndreyAnischik requested changes

2022-02-07 17:26 UTC, merged