feat: add validation on is logged in user for routes and registration…
MiBBy-4/ideas_api_frontend pull request #8
Opened 2022-02-24 20:13 UTC by MiBBy-4

…, login and logout buttons

2022-02-28 07:26 UTC, AndreyAnischik requested changes

2022-02-28 07:26 UTC, AndreyAnischik commented on src/App.jsx
> +        { state.isLoggedIn && state.customer.role === 3 ? (
can you please name the role here and move the value to a separate file with constants?

2022-02-28 07:26 UTC, AndreyAnischik commented on src/Idea/IdeaUpdateForm.jsx
> +    const { target: { value } } = event;
you can do it in one line: `const { target: { value, name } } = event;`

2022-02-28 07:26 UTC, AndreyAnischik commented on src/Idea/IdeaUpdateForm.jsx
> +}
space

2022-02-28 07:26 UTC, AndreyAnischik commented on src/apiRequests/AdminRequests.jsx
> +}
space

2022-03-03 07:40 UTC, AndreyAnischik requested changes

2022-03-03 07:40 UTC, AndreyAnischik commented on src/App.jsx
> +        { state.isLoggedIn && role === 3 ? (
what does 3 mean?

2022-03-03 07:45 UTC, MiBBy-4 commented on src/App.jsx
> +        { state.isLoggedIn && role === 3 ? (
There are three roles: businessman, investor and admin. So, I decided to do it with int number: 1, 2, 3. Number 3 is admin

2022-03-04 06:13 UTC, AndreyAnischik requested changes

2022-03-04 06:13 UTC, AndreyAnischik commented on src/App.jsx
> +        { state.isLoggedIn && role === 3 ? (
it is a magic number, move it at least to constant

2022-03-04 06:13 UTC, AndreyAnischik commented on src/Idea/IdeaShow.jsx
> +    if (today <= date && today >= date.setDate(date.getDate() - 10)) {
magic number 10

2022-03-04 06:57 UTC, AndreyAnischik commented on src/App.jsx
> +        { state.isLoggedIn && role === 3 ? (
There is still magic number here.

2022-03-04 06:58 UTC, AndreyAnischik requested changes

2022-03-04 06:58 UTC, AndreyAnischik commented on src/App.jsx
> +        { state.isLoggedIn && role === 3 ? (
constants should be stored in a separate file

2022-03-04 15:38 UTC, AndreyAnischik requested changes

2022-03-04 15:38 UTC, AndreyAnischik commented on src/apiRequests/IdeasRequests.jsx
>  export function setReaction(ideaId, reaction) {
why reactions are without `api/v1`?

2022-03-04 16:18 UTC, MiBBy-4 commented on src/apiRequests/IdeasRequests.jsx
>  export function setReaction(ideaId, reaction) {
Cause controller of reactions was out this folder, I changed it.

2022-03-05 14:15 UTC, AndreyAnischik requested changes

2022-03-05 14:15 UTC, AndreyAnischik commented on src/Idea/IdeaNewForm.jsx
> +    const { target: { value } } = event;
unite value and name in one destructuring

2022-03-06 09:40 UTC, AndreyAnischik requested changes

2022-03-06 09:40 UTC, AndreyAnischik commented on src/Idea/ReactionsCount.jsx
> +  reactions.map((reaction) => {
use reduce here

2022-03-06 09:40 UTC, AndreyAnischik commented on src/Idea/ReactionsCount.jsx
> +  reactions.map((reaction) => {
use reduce here

2022-03-11 04:50 UTC, AndreyAnischik approved these changes

2022-03-14 11:49 UTC, merged